#!/bin/sh
/bin/busybox mount -t proc proc /proc
/bin/busybox mount -t sysfs sysfs /sys
/bin/busybox mount -o remount,rw /
/bin/busybox mount -a
/bin/busybox --install -s
mkdir -p /dev/pts
mount -t devpts devpts /dev/pts
ifup -a

for i in /etc/init.d/S??*
do
	$i start
done
