#!/bin/sh
case "$1" in
	start)
		echo "Initializing mdev..."
		echo /sbin/mdev >/proc/sys/kernel/hotplug
		/sbin/mdev -s
		;;
	stop)
		;;
	restart)
		;;
	*)
		echo "Usage: $0 {start|stop|restart}"
		exit 1
		;;
esac
exit $?
